{"name": "Adding a product to cart", "status": "failed", "statusDetails": {"message": "selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 4s, while waiting for:\nbrowser.element(('xpath', '//span[@class=\"line-name__model\"]')).has text Nata\n\nReason: AssertionError: actual text: Ошейник\nScreenshot: file://C:\\Users\\natal\\.selene\\screenshots\\1683526734015\\1683526734015.png\nPageSource: file://C:\\Users\\natal\\.selene\\screenshots\\1683526734015\\1683526734015.html", "trace": "fn = <selene.core.conditions.ElementCondition object at 0x000001754C7E7460>\n\n    def logic(fn: Callable[[E], R]) -> R:\n        finish_time = time.time() + self._timeout\n    \n        while True:\n            try:\n>               return fn(self.entity)\n\nC:\\Python310\\lib\\site-packages\\selene\\core\\wait.py:119: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selene.core.conditions.ElementCondition object at 0x000001754C7E7460>\nentity = <selene.core.entity.Element object at 0x000001754C76D900>\n\n    def __call__(self, entity: E) -> None:\n>       return self._fn(entity)\n\nC:\\Python310\\lib\\site-packages\\selene\\core\\condition.py:173: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nentity = <selene.core.entity.Element object at 0x000001754C76D900>\n\n    def fn(entity: E) -> None:\n        query_to_str = str(query)\n        result = (\n            query.__name__ if query_to_str.startswith('<function') else query_to_str\n        )\n        actual = query(entity)\n        if not predicate(actual):\n>           raise AssertionError(f'actual {result}: {actual}')\nE           AssertionError: actual text: Ошейник\n\nC:\\Python310\\lib\\site-packages\\selene\\core\\condition.py:146: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <tests.test_cart.TestAddToCart object at 0x000001754D56BC10>\n\n    @allure.parent_suite(\"Web\")\n    @allure.severity(Severity.NORMAL)\n    @allure.suite(\"Cart\")\n    @allure.title(\"Adding a product to cart\")\n    def test_add_to_cart(self):\n        app.base.open_main_page()\n    \n        with allure.step('Do something'):\n            with allure.step('Goto Catalog'):\n                app.header_menu.choose_section(\"Каталог\")\n    \n            with allure.step('Choose product'):\n                app.catalog.choose_products_in_stock()\n                app.catalog.choose_random_product()\n                collection_name, article_name = app.product.remember_product()\n    \n            with allure.step('Choose size'):\n                app.product.select_size()\n    \n            with allure.step('Add to card'):\n                app.product.add_to_cart()\n    \n            with allure.step('Goto card'):\n                app.rightside_cart.submit_checkout()\n    \n            with allure.step('Check card'):\n>               app.checkout.assert_product_in_cart(collection_name, 'Nata')\n\ntest_cart.py:33: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\pages\\staya_dog\\checkout_page.py:12: in assert_product_in_cart\n    should(have.text(article_name))\nC:\\Python310\\lib\\site-packages\\selene\\core\\entity.py:136: in should\n    self.wait.for_(condition)\nC:\\Python310\\lib\\site-packages\\selene\\core\\wait.py:143: in for_\n    return self._decorator(self)(logic)(fn)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nfn = <selene.core.conditions.ElementCondition object at 0x000001754C7E7460>\n\n    def logic(fn: Callable[[E], R]) -> R:\n        finish_time = time.time() + self._timeout\n    \n        while True:\n            try:\n                return fn(self.entity)\n            except Exception as reason:\n                if time.time() > finish_time:\n                    reason_message = str(reason)\n    \n                    reason_string = '{name}: {message}'.format(\n                        name=reason.__class__.__name__,\n                        message=reason_message,\n                    )\n                    # TODO: think on how can we improve logging failures in selene, e.g. reverse msg and stacktrace\n                    # stacktrace = getattr(reason, 'stacktrace', None)\n                    timeout = self._timeout\n                    entity = self.entity\n    \n                    failure = TimeoutException(\n                        f'\\n'\n                        f'\\nTimed out after {timeout}s, while waiting for:'\n                        f'\\n{entity}.{fn}'\n                        f'\\n'\n                        f'\\nReason: {reason_string}'\n                    )\n    \n>                   raise self._hook_failure(failure)\nE                   selene.core.exceptions.TimeoutException: Message: \nE                   \nE                   Timed out after 4s, while waiting for:\nE                   browser.element(('xpath', '//span[@class=\"line-name__model\"]')).has text Nata\nE                   \nE                   Reason: AssertionError: actual text: Ошейник\nE                   Screenshot: file://C:\\Users\\natal\\.selene\\screenshots\\1683526734015\\1683526734015.png\nE                   PageSource: file://C:\\Users\\natal\\.selene\\screenshots\\1683526734015\\1683526734015.html\n\nC:\\Python310\\lib\\site-packages\\selene\\core\\wait.py:141: TimeoutException"}, "steps": [{"name": "Do something", "status": "failed", "statusDetails": {"message": "selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 4s, while waiting for:\nbrowser.element(('xpath', '//span[@class=\"line-name__model\"]')).has text Nata\n\nReason: AssertionError: actual text: Ошейник\nScreenshot: file://C:\\Users\\natal\\.selene\\screenshots\\1683526734015\\1683526734015.png\nPageSource: file://C:\\Users\\natal\\.selene\\screenshots\\1683526734015\\1683526734015.html\n\n", "trace": "  File \"C:\\QA_GURU\\demo_ui_tests_allure\\tests\\test_cart.py\", line 33, in test_add_to_cart\n    app.checkout.assert_product_in_cart(collection_name, 'Nata')\n  File \"C:\\QA_GURU\\demo_ui_tests_allure\\pages\\staya_dog\\checkout_page.py\", line 12, in assert_product_in_cart\n    should(have.text(article_name))\n  File \"C:\\Python310\\lib\\site-packages\\selene\\core\\entity.py\", line 136, in should\n    self.wait.for_(condition)\n  File \"C:\\Python310\\lib\\site-packages\\selene\\core\\wait.py\", line 143, in for_\n    return self._decorator(self)(logic)(fn)\n  File \"C:\\Python310\\lib\\site-packages\\selene\\core\\wait.py\", line 141, in logic\n    raise self._hook_failure(failure)\n"}, "steps": [{"name": "Goto Catalog", "status": "passed", "start": 1683526746595, "stop": 1683526747272}, {"name": "Choose product", "status": "passed", "start": 1683526747272, "stop": 1683526748963}, {"name": "Choose size", "status": "passed", "start": 1683526748963, "stop": 1683526749139}, {"name": "Add to card", "status": "passed", "start": 1683526749139, "stop": 1683526749378}, {"name": "Goto card", "status": "passed", "start": 1683526749378, "stop": 1683526749956}, {"name": "Check card", "status": "failed", "statusDetails": {"message": "selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 4s, while waiting for:\nbrowser.element(('xpath', '//span[@class=\"line-name__model\"]')).has text Nata\n\nReason: AssertionError: actual text: Ошейник\nScreenshot: file://C:\\Users\\natal\\.selene\\screenshots\\1683526734015\\1683526734015.png\nPageSource: file://C:\\Users\\natal\\.selene\\screenshots\\1683526734015\\1683526734015.html\n\n", "trace": "  File \"C:\\QA_GURU\\demo_ui_tests_allure\\tests\\test_cart.py\", line 33, in test_add_to_cart\n    app.checkout.assert_product_in_cart(collection_name, 'Nata')\n  File \"C:\\QA_GURU\\demo_ui_tests_allure\\pages\\staya_dog\\checkout_page.py\", line 12, in assert_product_in_cart\n    should(have.text(article_name))\n  File \"C:\\Python310\\lib\\site-packages\\selene\\core\\entity.py\", line 136, in should\n    self.wait.for_(condition)\n  File \"C:\\Python310\\lib\\site-packages\\selene\\core\\wait.py\", line 143, in for_\n    return self._decorator(self)(logic)(fn)\n  File \"C:\\Python310\\lib\\site-packages\\selene\\core\\wait.py\", line 141, in logic\n    raise self._hook_failure(failure)\n"}, "start": 1683526749956, "stop": 1683526754362}], "start": 1683526746595, "stop": 1683526754365}], "start": 1683526746081, "stop": 1683526754365, "uuid": "894a4f32-70f2-4643-bb6c-793b6431e5cb", "historyId": "ff54c28ef5a6d04435ef9df5c7b2ca3b", "testCaseId": "481a6b94dc93e1fe4f668b74fc7c13c5", "fullName": "tests.test_cart.TestAddToCart#test_add_to_cart", "labels": [{"name": "suite", "value": "Cart"}, {"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "Web"}, {"name": "subSuite", "value": "TestAddToCart"}, {"name": "host", "value": "LAPTOP-LLCB38HA"}, {"name": "thread", "value": "32012-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_cart"}]}